#!/usr/bin/env bash
# Installs and setup haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 164659-web-01 100.26.138.1 check
   server 164659-web-02 100.25.24.30 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
