#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

# Make a backup of /etc/hosts
sudo cp /etc/hosts /etc/hosts_backup

# Copy /etc/hosts to hosts.new
cp /etc/hosts ./hosts.new

# Replace occurrences of 127.0.0.1 with 127.0.0.2 in hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' hosts.new

# Append '8.8.8.8 facebook.com' after the line containing 127.0.0.2 in hosts.new
sed -i '/127.0.0.2/a'\
'8.8.8.8        facebook.com' hosts.new

# Overwrite /etc/hosts with hosts.new (with sudo to ensure proper permissions)
sudo cp -f ./hosts.new /etc/hosts
